In [4]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5']

array_list = np.array(object = list_)

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables

In [8]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [9]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data type of each element in list_:")
for i in list_:
    print(type(i))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for j in array_list:
    print(type(j))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.



In [10]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data type of each element in list_:")
for i in list_:
    print(type(i))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for j in array_list:
    print(type(j))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# new code 

In [12]:
# Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [13]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# Q4. Write a code to find the following characteristics of variable, num_array:

# (i) shape

# (ii) size

In [14]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Size of num_array
size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [16]:
zeros_array = np.zeros((3, 3))

print(zeros_array)

# Shape of num_array
shape = zeros_array.shape
print("Shape of num_array:", shape)

# Size of num_array
size = zeros_array.size
print("Size of num_array:", size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape of num_array: (3, 3)
Size of num_array: 9


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [18]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# THE END